### ISSUE TITLE
Не введено значение обязательного поля Наименование администрации

### ISSUE THREAD

**Issue by balya** [alexxxnf/passRest#1]
В любой ситуации выдает ошибку "Не введено значение обязательного поля Наименование администрации", хотя этого поля нет.

**Comment by alexxxnf** [comment]
К сожалению, я слишком давно не занимался Битриксом, чтобы понять, что это сообщение значит. 6 лет назад никакого поля "Наименование администрации" у пользователей не было.

Если сможете разобраться в чём дело и исправить, то я с радостью приму pull request.

**Comment by alexxxnf** [comment]
Похоже, это никому не интересно.
